source "https://rubygems.org"

gem "elixir-toolkit-theme-plugins", "~> 0.1.9"
gem "webrick", "~> 1.8.2"
gem "jekyll", "~> 4.3.2"
gem "jemoji", "~> 0.13.0"
gem "kramdown-parser-gfm", "~> 1.1"
gem "html-proofer", "~> 4.4.3"
gem "nokogiri", ">=1.18.8" # used by html-proofer, https://github.com/ResearchObject/ro-crate/security/dependabot/53

# fork of jekyll-feed where we prevent future posts being shown in the blog RSS feed
# see https://github.com/jekyll/jekyll-feed/pull/425 for status on the fix in the original gem
gem 'jekyll-feed', git: "https://github.com/elichad/jekyll-feed", branch: "hide-future-posts" 

group :jekyll_plugins do
  gem "jekyll-redirect-from", "~> 0.16.0"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-github-metadata", "~> 2.15"
  gem "jekyll-relative-links", "~> 0.6"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-remote-theme", "~> 0.4.3"
end
